# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Use Node.js 16.x'

- script: |
    npm cache clean --force
    rm -rf node_modules
    npm install
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm install graceful-fs
    node --max-old-space-size=4096 --max-semi-space-size=1024 node_modules/.bin/react-scripts build
  displayName: 'Build with Graceful-FS'

- task: CopyFiles@2
  inputs:
    contents: 'build/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files to Artifact Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: drop'