# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
  - group: az-router-vars

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Use Node.js 16.x'

- script: |
    npm cache clean --force
    rm -rf node_modules
    npm install
  displayName: 'npm install and build'

- script: |
    echo 'Creating .env file'
    echo "REACT_APP_API_URL=$(REACT_APP_API_URL)" >> $(Pipeline.Workspace)/.env
    echo "REACT_APP_ENV=$(REACT_APP_ENV)" >> $(Pipeline.Workspace)/.env
  displayName: 'Create .env File'

- script: |
    npm run build
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    contents: 'build/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files to Artifact Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: drop'