# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - az-router-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Create .env file with environment variables
      - name: Create .env file
        run: |
          Write-Host "Creating .env file with environment variables"
          $envVars = (Get-ChildItem Env: | Where-Object { $_.Name -match '^REACT_APP_' })
          $envVars | ForEach-Object { "$($_.Name)=$($_.Value)" } | Out-File -FilePath .env -Encoding utf8
        shell: pwsh

      # Print the contents of the .env file (Optional for Debugging)
      - name: Print .env file
        run: Get-Content .env
        shell: pwsh
      
      - name: npm install, build
        run: |
          npm cache clean --force
          npm install
          npm run build --if-present
     
      #Zip the build directory
      - name: zip release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          fileName: release.zip
          path: |
            ./build/*
            .env
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C281D91CE57D429CAF9BAEC7C838EA95 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_82B2627CABA94DB9B63B1A47DF65AEAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C27D7CA74AA48499231700AABB63B31 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'az-router-app'
          slot-name: 'Production'
          package: release.zip
          
